// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5oEDOqJrBbcO8owwrs5Gz53-S6RLGsMc',
    appId: '1:584017017251:web:dea1b8deddab06d9fd8216',
    messagingSenderId: '584017017251',
    projectId: 'evently-c16-project',
    authDomain: 'evently-c16-project.firebaseapp.com',
    storageBucket: 'evently-c16-project.firebasestorage.app',
    measurementId: 'G-GV91BG0KV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlVEjs23_6IUrOnkghPuWN4bW-giG1q44',
    appId: '1:584017017251:android:8dab1afac7d11d6bfd8216',
    messagingSenderId: '584017017251',
    projectId: 'evently-c16-project',
    storageBucket: 'evently-c16-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGpWW9wbCahtctRDuyXtsED11Ap2PbpnI',
    appId: '1:584017017251:ios:964b6fddeb3166f9fd8216',
    messagingSenderId: '584017017251',
    projectId: 'evently-c16-project',
    storageBucket: 'evently-c16-project.firebasestorage.app',
    iosClientId: '584017017251-f5hp2el5jnjkvihvog88duusibgo5hbb.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventlyC16Sun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGpWW9wbCahtctRDuyXtsED11Ap2PbpnI',
    appId: '1:584017017251:ios:964b6fddeb3166f9fd8216',
    messagingSenderId: '584017017251',
    projectId: 'evently-c16-project',
    storageBucket: 'evently-c16-project.firebasestorage.app',
    iosClientId: '584017017251-f5hp2el5jnjkvihvog88duusibgo5hbb.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventlyC16Sun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5oEDOqJrBbcO8owwrs5Gz53-S6RLGsMc',
    appId: '1:584017017251:web:0072f56b4b36b7b2fd8216',
    messagingSenderId: '584017017251',
    projectId: 'evently-c16-project',
    authDomain: 'evently-c16-project.firebaseapp.com',
    storageBucket: 'evently-c16-project.firebasestorage.app',
    measurementId: 'G-P3NLXQ9N9Q',
  );

}